services:
  notification:
    build:
      dockerfile: notification/.docker/Dockerfile.dev.multistage
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - ${EXPOSE_DEBUG_PORT}:${DEBUG_PORT}