networks:
  ticket-system:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "${EXPOSE_ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_PORT}
    networks:
      - ticket-system

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "${BROKER_1_OUT_PORT}:${BROKER_1_OUT_PORT}"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_LISTENERS=INTERNAL://kafka-broker-1:${BROKER_1_INT_PORT},OUTSIDE://0.0.0.0:${BROKER_1_OUT_PORT}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-1:${BROKER_1_INT_PORT},OUTSIDE://localhost:${BROKER_1_OUT_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - ticket-system

  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "${BROKER_2_OUT_PORT}:${BROKER_2_OUT_PORT}"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_LISTENERS=INTERNAL://kafka-broker-2:${BROKER_2_INT_PORT},OUTSIDE://0.0.0.0:${BROKER_2_OUT_PORT}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-broker-2:${BROKER_2_INT_PORT},OUTSIDE://localhost:${BROKER_2_OUT_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - ticket-system