networks:
  ticket-system:
    driver: bridge

services:
  event:
    build:
      context: ../event
      dockerfile: ../event/.docker/Dockerfile
    ports:
      - 50600:50600
    networks:
      - ticket-system
    depends_on:
      - event_db
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:postgres@event_db:5432/event

  event_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ../event/.docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event
    networks:
      - ticket-system
    restart: unless-stopped
